version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: qmag-nav:latest
    container_name: qmag-nav-api
    ports:
      - "8000:8000"
    volumes:
      - ./mag_data:/app/mag_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info

  locust:
    image: locustio/locust
    container_name: qmag-nav-locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://api:8000
    depends_on:
      - api
    profiles:
      - loadtest